package csr

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*SignCsrOK Successful response

swagger:response signCsrOK
*/
type SignCsrOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewSignCsrOK creates SignCsrOK with default headers values
func NewSignCsrOK() *SignCsrOK {
	return &SignCsrOK{}
}

// WithPayload adds the payload to the sign csr o k response
func (o *SignCsrOK) WithPayload(payload string) *SignCsrOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sign csr o k response
func (o *SignCsrOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignCsrOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
