package ca

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ihgs/private_ca/models"
)

/*CreateCAOK Successful response

swagger:response createCAOK
*/
type CreateCAOK struct {
}

// NewCreateCAOK creates CreateCAOK with default headers values
func NewCreateCAOK() *CreateCAOK {
	return &CreateCAOK{}
}

// WriteResponse to the client
func (o *CreateCAOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*CreateCAGone Error Response

swagger:response createCAGone
*/
type CreateCAGone struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewCreateCAGone creates CreateCAGone with default headers values
func NewCreateCAGone() *CreateCAGone {
	return &CreateCAGone{}
}

// WithPayload adds the payload to the create c a gone response
func (o *CreateCAGone) WithPayload(payload *models.ErrorModel) *CreateCAGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create c a gone response
func (o *CreateCAGone) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCAGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
