/* 
 * Private CA for Test
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pca

type Subject struct {

	// Country Name (2 letter code)
	CountryName string `json:"country_name,omitempty"`

	// State or Province Name (full name)
	StateOfProvince string `json:"state_of_province,omitempty"`

	// Locality Name (eg, city)
	LocalityName string `json:"locality_name,omitempty"`

	// Organization Name (eg, company)
	OrgName string `json:"org_name,omitempty"`

	// Organizational Unit Name (eg, section)
	OrgUnit string `json:"org_unit,omitempty"`

	// Common Name (eg, your name or your server\\'s hostname)
	CommonName string `json:"common_name,omitempty"`

	// Email Address
	Email string `json:"email,omitempty"`

	// A challenge password
	ChallengePassword string `json:"challenge_password,omitempty"`

	// An optional company name
	OptionalCompanyName string `json:"optional_company_name,omitempty"`
}
