# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: Private CA for Test

basePath: /api/v1alpha
# Describe your paths here
paths:
  /ca:
    post:
      description: |
        Create CA
      operationId: createCA
      produces:
        - application/json
      parameters:
        -
          name: certificate_authority
          in: body
          description: Certificate Subject
          required: true
          schema:
            $ref: '#/definitions/certificate_authority'
      responses:
        200:
          description: Successful response

        410:
          description: Error Response
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  certificate_authority:
    type: object
    properties:
      pem_password:
        type: string
        description: PEM pass phrase
      subject:
        $ref: '#/definitions/subject'
      days:
        type: integer
        default: 365
        format: int32
      cdays:
        type: integer
        default: 1095
        format: int32
  subject:
    type: object
    required:
      - country_name
      - state_of_province
      - locality_name
      - org_name
      - org_unit
      - common_name
      - email
    properties:
      country_name:
        type: string
        description: Country Name (2 letter code)
        default: JP
      state_of_province:
        type: string
        description: State or Province Name (full name)
        default: Default Province
      locality_name:
        type: string
        description: Locality Name (eg, city)
        default: Default City
      org_name:
        type: string
        description: Organization Name (eg, company)
        default: Default Company Ltd
      org_unit:
        type: string
        description: Organizational Unit Name (eg, section)
        default: Test Unit
      common_name:
        type: string
        description: Common Name (eg, your name or your server\'s hostname)
        default: "*.local"
        maxLength: 64
      email:
        type: string
        description: Email Address
        maxLength: 64
        default: ca@example.com
      challenge_password:
        type: string
        description: A challenge password
        minLength: 4
        maxLength: 20
      optional_company_name:
        type: string
        description:  An optional company name
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
