package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// CertificateAuthority certificate authority
// swagger:model certificate_authority
type CertificateAuthority struct {

	// cdays
	Cdays *int32 `json:"cdays,omitempty"`

	// days
	Days *int32 `json:"days,omitempty"`

	// PEM pass phrase
	PemPassword string `json:"pem_password,omitempty"`

	// subject
	Subject *Subject `json:"subject,omitempty"`
}

// Validate validates this certificate authority
func (m *CertificateAuthority) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubject(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CertificateAuthority) validateSubject(formats strfmt.Registry) error {

	if swag.IsZero(m.Subject) { // not required
		return nil
	}

	if m.Subject != nil {

		if err := m.Subject.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
